import React from 'react';
import { useGame } from '../context/GameContext';
import { GameView } from '../types';
import PlayerCard from './PlayerCard';
import { ArrowRight, Trophy, Users, TrendingUp } from 'lucide-react';

const Dashboard: React.FC = () => {
  const { state, setView } = useGame();
  
  return (
    <div className="p-8 max-w-7xl mx-auto space-y-8 animate-fade-in">
        {/* Header Stats */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div className="bg-slate-800 p-4 rounded-xl border border-white/5">
                <div className="text-gray-400 text-xs uppercase font-bold mb-1">Funds</div>
                <div className="text-2xl text-green-400 font-mono font-bold">£{(state.manager.funds/1000000).toFixed(1)}M</div>
            </div>
            <div className="bg-slate-800 p-4 rounded-xl border border-white/5">
                <div className="text-gray-400 text-xs uppercase font-bold mb-1">League Pos</div>
                <div className="text-2xl text-white font-bold">1st</div>
            </div>
            <div className="bg-slate-800 p-4 rounded-xl border border-white/5">
                <div className="text-gray-400 text-xs uppercase font-bold mb-1">Next Match</div>
                <div className="text-lg text-blue-300 font-bold truncate">{state.nextOpponent.name}</div>
            </div>
            <div className="bg-slate-800 p-4 rounded-xl border border-white/5">
                <div className="text-gray-400 text-xs uppercase font-bold mb-1">Manager Rep</div>
                <div className="text-2xl text-yellow-400 font-bold">{state.manager.reputation}</div>
            </div>
        </div>

        {/* Hero Section */}
        <div className="bg-gradient-to-r from-blue-900 to-slate-900 rounded-2xl p-8 border border-white/10 relative overflow-hidden">
             <div className="relative z-10">
                 <h1 className="text-4xl font-bold text-white mb-2">Matchday {state.week}</h1>
                 <p className="text-blue-200 mb-6 max-w-lg">Your team is ready. The AI Assistant is online to help with real-time tactical decisions during the game.</p>
                 <div className="flex gap-4">
                     <button onClick={() => setView(GameView.MATCH)} className="bg-white text-blue-900 px-8 py-3 rounded-lg font-bold hover:bg-gray-100 flex items-center gap-2">
                         Play Match <ArrowRight size={18} />
                     </button>
                     <button onClick={() => setView(GameView.TACTICS)} className="bg-blue-800/50 text-white px-6 py-3 rounded-lg font-bold border border-blue-400/30 hover:bg-blue-800">
                         Adjust Tactics
                     </button>
                 </div>
             </div>
             <Trophy className="absolute -right-10 -bottom-10 w-64 h-64 text-white/5 rotate-12" />
        </div>

        {/* Squad Preview */}
        <div>
            <div className="flex justify-between items-center mb-4">
                <h2 className="text-xl font-bold text-white flex items-center gap-2"><Users size={20}/> Top Performers</h2>
                <button onClick={() => setView(GameView.SQUAD)} className="text-sm text-blue-400 hover:text-white">View Squad &rarr;</button>
            </div>
            <div className="flex gap-4 overflow-x-auto pb-4">
                {state.team.roster.slice(0, 5).map(p => (
                    <PlayerCard key={p.id} player={p} />
                ))}
            </div>
        </div>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
             <div className="bg-slate-800/50 border border-white/5 p-6 rounded-xl hover:bg-slate-800 cursor-pointer group" onClick={() => setView(GameView.VEO_STUDIO)}>
                 <div className="w-12 h-12 bg-purple-900/50 rounded-lg flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                     <span className="text-2xl">🎥</span>
                 </div>
                 <h3 className="text-lg font-bold text-white mb-1">Veo Highlight Studio</h3>
                 <p className="text-sm text-gray-400">Generate realistic video replays or cinematic shots of your players using Google Veo AI.</p>
             </div>
             
             <div className="bg-slate-800/50 border border-white/5 p-6 rounded-xl hover:bg-slate-800 cursor-pointer group">
                 <div className="w-12 h-12 bg-green-900/50 rounded-lg flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                     <span className="text-2xl">📈</span>
                 </div>
                 <h3 className="text-lg font-bold text-white mb-1">Youth Academy</h3>
                 <p className="text-sm text-gray-400">Scout next-gen talent. Faces and stats generated by Gemini.</p>
             </div>
        </div>
    </div>
  );
};

export default Dashboard;